### PR TITLE
Update docs with Wagmi v2 changes

### LINKED ISSUE #60: Wagmi V2 docs update
### Description : 

Just sharing some updates that are on top of my mind : 

### Updating wagmi/viem links:

Updating wagmi and viem links to point to new docs

### Renaming:

useScaffoldContractRead => useScaffoldReadContract
useScaffoldContractWrite => useScaffoldWriteContract

In `useScaffoldEventSubscriber` changes the `listner` name => `onLogs`

We need to also update `# Configuration` with link pointing to new docs and that hook's wagmi configuration.

### useScaffoldWriteContract:

Update example, now you have to always kind of pass stuff the way we used to do in imperative way.

<details>
  <summary>
Example :
  </summary>

```tsx
const { writeContractAsync: writeYourContractAsync } =
  useScaffoldWriteContract("YourContract");

<button
  className="btn btn-primary btn-md"
  onClick={async () => {
    try {
      await writeYourContractAsync({
        functionName: "setGreeting",
        args: [newGreeting],
        value: parseEther("0.2"),
      });
    } catch (error) {
      console.error("Error setting greeting", error);
    }
  }}
>
  Send TX
</button>;
```

</details>

### Update Recipes: 

Update recipes inline with new version 

--- 

Just for reference if we have too look for example, I tried using most commonly used stuff in SE-2 at  [`page.tsx`](https://github.com/scaffold-eth/scaffold-eth-2/blob/wagmi-v2-test/packages/nextjs/app/page.tsx) 

Also happy to help and collaborate on this 🙌

### PR DESCRIPTION
**Pull request by Pabl0cks**
Creating this draft to start working on #60 to adapt docs to all changes involved with [SE2 Wagmi v2 migration](https://github.com/scaffold-eth/scaffold-eth-2/pull/700)

- [X] Update wagmi docs links to v2
- [X] Update viem docs links to v2
- [x] Update custom hooks names, params and examples to wagmi v2
- [x] Update recipes

Closes #60

### CODE REVIEW

**Comment by Pabl0cks** [comment]
> Maybe add a small section about upgrading a Wagmi v1 SE-2 project to a Wagmi v2 SE-2 project?

I think Damu's idea in [#60](https://github.com/scaffold-eth/se2-docs/issues/60#issuecomment-2037500434) can be helpful for people wanting to migrate to latest SE-2 version, without having to check all details of wagmi v2 migration. 
Let me know if you think it's interesting and I'll prepare a draft version for that guide 🙌, we could add it at the end of hooks menu.

Some doubts I had when I was documenting the changes:
- In `useScaffoldWriteContract` doc I'm instanciating `writeContractAsync` into `writeYourContractAsync`, not sure if it's the right practice for the docs. 
- In recipes (`WagmiContractWriteWithFeedback` and `WriteToContractWriteAsyncButton`) I was not sure about putting the `writeContractAsyncWithParams` into the event handler or not. Did not put it for simplicity of the example, but don't know if it's a good practice for a "real world" example

Hope I haven't missed any changes, and that my explanations are not terrible 😅

**Review by technophile-04 — APPROVED** [review]
TYSM @Pabl0cks !! This is really great !!! 

Just pushed a few commits tried keeping them atomic so its easy to read, mainly revolving around : 

1. Distinguishing that contract interaction args are now passed to `writeContractAsync` instead of `useSWC` eg: https://github.com/scaffold-eth/se2-docs/pull/61/commits/38d8085e1188d6ac58301c01e4963930c039bb15, https://github.com/scaffold-eth/se2-docs/pull/61/commits/d0c172a03f0f6eaf534ecee602444c586c2986a2
2. Wrapping `writeContractAsync` inside `try/catch` its important we mention this, earlier it not imp but after https://github.com/scaffold-eth/scaffold-eth-2/pull/758 you should do it. 
   - EG: [Austin getting unhandled error](https://youtu.be/WiqZMtJ1LJw?si=pWIclmI2zFdzW6Jw&t=780) on Next page (bottom left of his page) since he didn't wrap the function 

I think this is nicely ready to merge along with https://github.com/scaffold-eth/scaffold-eth-2/pull/700 🙌

**Comment by Pabl0cks** [comment]
Thanks for the awesome review @technophile-04!! 

Love all the improvements and learnt from the fixes 🙌

**Comment by technophile-04** [comment]
Merging this, we already merged https://github.com/scaffold-eth/scaffold-eth-2/pull/700 

Tysm @Pabl0cks again !!

**Pull request merged**
