### PR TITLE
Update docs to current README version

### PR DESCRIPTION
**Pull request by Pabl0cks**
Creating PR to add the last changes of Scaffold-eth 2 README into Docs site

### CODE REVIEW

**Comment by Pabl0cks** [comment]
Just pushed changes to have Docs with the last changes in SE-2 README.

**Comment by carletex** [comment]
@Pabl0cks we probably want to split this into different PRs.

The ToDoS that you have here could be split into issues.

This PR could be just "Update docs to current README version"

**Comment by Pabl0cks** [comment]
> The ToDoS that you have here could be split into issues.
>
> This PR could be just "Update docs to current README version"

You're right! Let's get this done first, I've just updated the PR and created the Issues 🙌

**Comment by Pabl0cks** [comment]
With the current content of our Scaffold-eth 2 README, I feel some items of our Docs sidebar have too much depth, since the content of each of them ends being too small. 

For example at Configuration, I feel having only 1 entry in the sidebar (just the parent), and having the rest of the items as "h2" inside the parent content, may be more useful for the user in this case. Plus Docusaurus adds the right content menu with the "h2" titles. 

With current granulation:
Configuration-GranularSidebar

Compacted in 1 sidebar element:
Configuration-CompactSidebar

What do you think? If you prefer compact one, we can try also with "Interacting / Hooks" and see if it works better or worse.

**Comment by Pabl0cks** [comment]
Just pushed my config file to solve #4

**Comment by carletex** [comment]
@Pabl0cks 

> What do you think?

I like it! Also not sure if we need the word "Configuration"? 

>  We can try also with "Interacting / Hooks" and see if it works better or worse.

This doesn't bother me as much. We can just see how it feels to change the compact "type error" section one and decide later on this.

**Comment by technophile-04** [comment]
@Pabl0cks we just merged https://github.com/scaffold-eth/scaffold-eth-2/pull/460/files

Could just update `useScaffoldContract` section too, thanks 🙌: 
Screenshot 2023-08-02 at 7 36 01 PM

**Comment by edakturk14** [comment]
amazing @Pabl0cks, tysm! Sorry the configuration word is from me :D we could remove it, I agree with the direction here. 

> @Pabl0cks we just merged https://github.com/scaffold-eth/scaffold-eth-2/pull/460/files

> 
> Could you just update `useScaffoldContract` section too, thanks 🙌: Screenshot 2023-08-02 at 7 36 01 PM

thanks @technophile-04 for mentioning this, agree with the addition we can update the docs

**Comment by Pabl0cks** [comment]
Thanks for the fast review @carletex @technophile-04 and @edakturk14 ♥

> I like it! Also not sure if we need the word "Configuration"?
> ++ I think we can remove it

Great! I've just pushed the compacted version with "Configuration" removed.

> This doesn't bother me as much. We can just see how it feels to change the compact "type error" section one and decide later on this.
> I like the current one(having them separate) because having them separate visually makes its easy to view all available hooks and easy to navigate

Ok! With current sidebar menu size and number of hooks I like them showing too, we can always re-evaluate in the future if needed.

> For some reason Shipping Your dApp section just after Welcome to SE-2 doesn't look good to me 😅, Maybe we move it below Configuration: Disabling type and lininting error checks or at least have it after QuickStart?
> 💯 agree! I'll add it after Quickstart or after the hooks.

Ups! My bad, it was after Quickstart in the prod version and somehow I moved it before that section. Fixed!

> Could you just update useScaffoldContract section too, thanks 🙌:

Updated with last changes, thanks for the quick warning! 🙌

__One last change pushed:__ I have compacted "Deploy your NextJS App" to have "Scaffold App Configuration" as H2, to remove 3rd level of depth in the menu. If you don't like that change, we can go to the previous version 😊

If you see everything OK, lets merge it and keep iterating!! 🚀🔥 :D

**Comment by carletex** [comment]
Thank you all!! Looking good for a merge :)

image

Vercel preview deployments are amazing, so you can see how it will look when deployed.

I'll open a few minor issues regarding styling.

**Pull request merged**
