### PR TITLE
Update intro.md with links to documentation of main components.

### PR DESCRIPTION
**Pull request by OwlWilderness**
Added links to the documentation of main components in the intro.md

See Issue https://github.com/scaffold-eth/se2-docs/issues/27

### CODE REVIEW

**Comment by technophile-04** [comment]
Thanks @OwlWilderness 🙌, I think this makes sense to me! 

@OwlWilderness could you please resolve the conflicts, also let's see what others have to say

**Comment by carletex** [comment]
Lgtm!

> [Hardhat](https://hardhat.org/docs) for running local networks, deploying and testing smart contracts.

Should we add Foundry here? Like «Hardhat or Foundry for running local networks, deploying and testing smart contracts.»

Or should we wait until CLI branch is merged?

**Comment by carletex** [comment]
lol, never mind. It'll be there when fixing the conflicts :)

**Comment by edakturk14** [comment]
lgtm as well w/conflicts fixed! Thank you @OwlWilderness!!

**Comment by OwlWilderness** [comment]
Thank you all.

**Comment by technophile-04** [comment]
Looks good, Thanks @OwlWilderness merging this 🙌

**Pull request merged**
